// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAstw4X8ebXFVTUXhLjXa0zfF6WxPRyaGg',
    appId: '1:728739790069:android:8a43e5b9834d30b86919bc',
    messagingSenderId: '728739790069',
    projectId: 'projeto-integrador3-442ef',
    storageBucket: 'projeto-integrador3-442ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5pu6gLObVmi80Tc9CvwR-3KICZwwGbVc',
    appId: '1:728739790069:ios:a74d7173f96b59666919bc',
    messagingSenderId: '728739790069',
    projectId: 'projeto-integrador3-442ef',
    storageBucket: 'projeto-integrador3-442ef.appspot.com',
    iosClientId: '728739790069-cooj0g3fk75grranj3h47jclhc3uuqaf.apps.googleusercontent.com',
    iosBundleId: 'br.com.Sorriso24h.edu.puccampinas.sorriso24hcliente',
  );
}
